# Generated by Django 3.1.5 on 2021-02-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_research_backend', '0003_auto_20210208_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listentry',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oebl_research_backend.list'),
        ),
    ]
